import type { Metadata } from "next";
import ClientesLayout from "@/components/layouts/ClientesLayout";
import "../globals.css";

export const metadata: Metadata = {
  title: "Gymstem | Rutina",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <ClientesLayout>{children}</ClientesLayout>;
}
